name: publish-sponsors
on:
    workflow_dispatch:
    schedule:
        - cron: 30 15 * * *

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Generate Sponsors 💖
              uses: JamesIves/github-sponsors-readme-action@v1
              with:
                  token: ${{ secrets.PAT }}
                  organization: true
                  file: 'README.md'

            - name: Deploy to GitHub Pages 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: master
                  folder: '.'